# This is a basic workflow to help you get started with Actions

name: tranquil-2020-ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore: ['.vscode/**']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: fetch all history and tags from all branches for gitversion
      run: git fetch --prune --unshallow

    - name: install gitversion tool
      uses: gittools/actions/gitversion/setup@v0.9
      with:
          versionSpec: '5.1.x'
      
    - name: execute gitversion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9
        
    - name: print gitversion
      run: |
        echo "Major: ${{ steps.gitversion.outputs.major }}"
        echo "Minor: ${{ steps.gitversion.outputs.minor }}"
        echo "Patch: ${{ steps.gitversion.outputs.patch }}"
        echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
        echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
        
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: clean install dependencies
      run: npm ci
    
    - name: compile and create vsix
      run: npm run package

    - name: print vsix path
      run: |
        echo "VSIX Path: ${{ env.vsix_path }}"
        
    - name: upload vsix as artifact
      uses: actions/upload-artifact@v1
      with:
        name: tranquil-2020-${{github.run_id}}.vsix
        path: ${{github.workspace}}/tranquil-2020-${{0.1.0}}.vsix
      
    - name: publish to marketplace
      if: github.ref == 'refs/heads/master'
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      
   
